[package]
name = "multicast-discovery-socket"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10.9"
log = "0.4.27"
socket2 = "0.5.10"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.30.1", features = ["socket", "net", "uio"] }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ['mswsock', 'iphlpapi', 'inaddr', 'iptypes', 'winerror', 'minwindef', 'ws2def', 'ws2ipdef', 'winsock2'] }

[target.'cfg(any(windows, linux))'.dependencies]
if-addrs = "0.13.4"

[dev-dependencies]
simple_logger = "5.0.0"
